version: '3.7'
services:
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    container_name: chat-backend
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
  db:
    image: mongo
    container_name: chat-db
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    volumes:
      - ./data/db:/data/db